stage = "local_training"
experiment_name = "local_bank_2_banksim"
output_dir = "data/experiments"
model_config = "configs/shared/model.toml"

institution_id = "bank_2"
dataset_path = "data/train_test_splits/bank_2_train.csv"

local_epochs = 20
learning_rate = 0.016
fraud_weight = 14
batch_size = 4096 # (or 256 should be fine too (optuna))
classification_threshold = 0.5
seed = 42
