stage = "evaluation"
experiment_name = "eval_fincl_bank1"
output_dir = "data/experiments"
model_path = "data/experiments/federated_global/model.pt"
dataset_path = "data/train_test_splits/bank_1_test.csv"
classification_threshold = 0.5
