output_dir = "data/train_test_splits"
test_fraction = 0.2
seed = 42

[[institutions]]
institution_id = "bank_1"
dataset_path = "configs/harmonized_data/bank_a_sparkov.csv"

[[institutions]]
institution_id = "bank_2"
dataset_path = "configs/harmonized_data/bank_b_banksim.csv"

[[institutions]]
institution_id = "bank_3"
dataset_path = "configs/harmonized_data/bank_c_ccfraud.csv"
