experiment_name = "sample_inference"
output_dir = "data/experiments"
checkpoint_path = "data/experiments/federated_global/model.pt"
model_type = "tabnet"
input_data_path = "configs/sample_data/bank_1.csv"

tabnet_decision_dim = 16
tabnet_attention_dim = 16
tabnet_steps = 3
tabnet_relaxation_factor = 1.5
tabnet_sparsity_weight = 0.0001
