experiment_name = "local_bank_2_banksim"
output_dir = "data/experiments"
model_config = "configs/model.toml"

institution_id = "bank_2"
dataset_path = "data/train_test_splits/bank_2_train.csv"

local_epochs = 5
learning_rate = 0.02
fraud_weight = 10
batch_size = 256
classification_threshold = 0.5
seed = 42
