experiment_name = "bank_a_sparkov"
output_dir = "data/experiments"
model_config = "configs/model.toml"

institution_id = "bank_1"
dataset_path = "data/train_test_splits/bank_1_train.csv"

local_epochs = 5
learning_rate = 0.01
fraud_weight = 10
batch_size = 256
classification_threshold = 0.7
seed = 42
