stage = "evaluation"
experiment_name = "eval_fexcl3_bank3"
output_dir = "data/experiments"
model_path = "data/experiments/federated_banks_1_2/model.pt"
dataset_path = "data/train_test_splits/bank_3_test.csv"
classification_threshold = 0.5
