stage = "model_matrix_evaluation"
experiment_name = "model_matrix_evaluation"
output_dir = "data/experiments"
classification_threshold = 0.5

[[datasets]]
dataset_id = "bank_1"
path = "data/mixed_datasets/test/bank_1_dominant_33_33_33.csv"

[[datasets]]
dataset_id = "bank_2"
path = "data/mixed_datasets/test/bank_2_dominant_33_33_33.csv"

[[datasets]]
dataset_id = "bank_3"
path = "data/mixed_datasets/test/bank_3_dominant_33_33_33.csv"




[[local_models]]
model_id = "local_bank_1"
base_path = "data/experiments/local_bank_1_tabnet"
run_number = 1

[[local_models]]
model_id = "local_bank_2"
base_path = "data/experiments/local_bank_2_banksim"
run_number = 1

[[local_models]]
model_id = "local_bank_3"
base_path = "data/experiments/local_bank_3_ccfraud"
run_number = 1



[global_federated_model]
model_id = "federated_global"
base_path = "data/experiments/federated_global"
run_number = 1



[[exclusive_federated_models]]
model_id = "federated_exclusive_bank_3"
base_path = "data/experiments/federated_banks_1_2"
run_number = 1

[[exclusive_federated_models]]
model_id = "federated_exclusive_bank_2"
base_path = "data/experiments/federated_banks_1_3"
run_number = 1

[[exclusive_federated_models]]
model_id = "federated_exclusive_bank_1"
base_path = "data/experiments/federated_banks_2_3"
run_number = 1





[[exclusive_ensembles]]
model_id = "ensemble_exclusive_bank_1"
local_model_id = "local_bank_1"
federated_model_id = "federated_exclusive_bank_1"
config_path = "configs/ensemble/exclusive/bank_1.toml"

[[exclusive_ensembles]]
model_id = "ensemble_exclusive_bank_2"
local_model_id = "local_bank_2"
federated_model_id = "federated_exclusive_bank_2"
config_path = "configs/ensemble/exclusive/bank_2.toml"

[[exclusive_ensembles]]
model_id = "ensemble_exclusive_bank_3"
local_model_id = "local_bank_3"
federated_model_id = "federated_exclusive_bank_3"
config_path = "configs/ensemble/exclusive/bank_3.toml"

[[inclusive_ensembles]]
model_id = "ensemble_inclusive_bank_1"
local_model_id = "local_bank_1"
federated_model_id = "federated_global"
config_path = "configs/ensemble/inclusive/bank_1.toml"

[[inclusive_ensembles]]
model_id = "ensemble_inclusive_bank_2"
local_model_id = "local_bank_2"
federated_model_id = "federated_global"
config_path = "configs/ensemble/inclusive/bank_2.toml"

[[inclusive_ensembles]]
model_id = "ensemble_inclusive_bank_3"
local_model_id = "local_bank_3"
federated_model_id = "federated_global"
config_path = "configs/ensemble/inclusive/bank_3.toml"
