stage = "evaluation"
experiment_name = "eval_local_bank2"
output_dir = "data/experiments"
model_path = "data/experiments/local_bank_2_banksim/run_002/model.pt"
dataset_path = "data/train_test_splits/bank_2_test.csv"
classification_threshold = 0.5
