stage = "evaluation"
experiment_name = "eval_local_bank1"
output_dir = "data/experiments"
model_path = "data/experiments/local_bank_1_tabnet/model.pt"
dataset_path = "data/train_test_splits/bank_1_test.csv"
classification_threshold = 0.5
